name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: |
          echo "Hello!"
          echo "WORLD"
      
      - name: Print gb
        run: echo "GB!"
      
