name: First workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest

    container:
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print pwd
        run: apt install clinfo
